import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";
import TanstackProvider from "@/providers/TanstackProvider";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Sidebar />
        <div className="p-4 sm:ml-64">
          <div className="p-4 shadow-xl border border-gray-200 dark:border-gray-700 mt-14">
            <TanstackProvider>{children}</TanstackProvider>
            <Toaster />
          </div>
        </div>
      </body>
    </html>
  );
}
